### ISSUE TITLE
После запуска не загрузился базовый шаблон

### ISSUE THREAD

**Issue by SergeyMi37** [natkaida/blogit#6]
После запуска не загрузился базовый шаблон
![image](https://github.com/natkaida/blogit/assets/18187317/b2c62527-5753-4e27-8795-7ff74f867e4a)

Админка работает нормально

**Comment by natkaida** [comment]
Настройки для разработки (не для продакшена) в **config/settings.py** :

```
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
```

**Comment by SergeyMi37** [comment]
Не помогло
(venv) student@st:~/App/blogit$ python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/student/App/blogit/venv/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/student/App/blogit/venv/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "/home/student/App/blogit/venv/lib/python3.8/site-packages/django/core/management/base.py", line 546, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
?: (staticfiles.E002) The STATICFILES_DIRS setting should not contain the STATIC_ROOT setting.

System check identified 1 issue (0 silenced).

**Comment by SergeyMi37** [comment]
Помогло так.
STATIC_ROOT = BASE_DIR / "staticfiles"

**Comment by XJIeb** [comment]
#STATIC_ROOT = os.path.join(BASE_DIR, 'collected_static/')

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')] 

не знаю стоит ли писать но вдруг, я python manage.py collectstatic писал еще

А так проект стоящий, понравилась реализация. Красиво сделано
